'''title'''
__title__ = 'imagecompression'
'''description'''
__description__ = 'Imagecompression: Image compressors written by pure python.'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/imagecompression'
'''version'''
__version__ = '0.1.0'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Copyright 2022 Zhenchao Jin'