'''title'''
__title__ = 'pyimagecompressor'
'''description'''
__description__ = 'ImageCompressor: Image compressors written by pure python.'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/imagecompressor'
'''version'''
__version__ = '0.1.1'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2022 Zhenchao Jin'